const movies = [
"Jailer","Leo","Vikram","Master","Kaithi","Thalapathi","Baasha","Annamalai","Padayappa",
"Sivaji","Enthiran","Kabali","Petta","Darbar","Annaatthe",
"Soorarai Pottru","Jai Bhim","Asuran","Karnan","Visaranai",
"Pariyerum Perumal","Aadukalam","Kaala","Madras","Sarpatta Parambarai",
"Theri","Mersal","Bigil","Ghilli","Thuppakki","Kaththi",
"Pokiri","Nanban","Beast","Varisu",
"7aum Arivu","Billa","Billa 2","Arrambam","Yennai Arindhaal","Vedalam",
"Viswasam","Valimai","Thunivu",
"Singam","Singam 2","Singam 3","Ayan","Maattrraan","Kaappaan","NGK",
"Anjaan","24","Mass","Pasanga","Pasanga 2","Ratsasan",
"Remo","Doctor","Don","Ethir Neechal","Maari","Maari 2","VIP","VIP 2",
"Thiruchitrambalam","Vaathi","Captain Miller","Jagame Thandhiram",
"Pudhupettai","Mayakkam Enna","Polladhavan","Kodi","Anegan","Thodari",
"Alaipayuthey","Minnale","Vaaranam Aayiram","Kaakha Kaakha",
"Vettaiyaadu Vilaiyaadu","Achcham Yenbadhu Madamaiyada","OK Kanmani",
"96","Seethakathi","Pizza","Pizza 2","Iraivi","Jigarthanda","Jigarthanda DoubleX",
"Super Deluxe","Panchathanthiram","Michael Madana Kama Rajan","Thenali","Avvai Shanmugi",
"Nayakan","Mahanadhi","Indian","Indian 2","Devar Magan",
"Dasavathaaram","Hey Ram","Virumaandi","Apoorva Sagodharargal",
"Sathya","Anbe Sivam","Roja","Bombay","Iruvar","Guru",
"Kadhal","Kadhalukku Mariyadhai","Kadhal Desam","Kadhal Konden",
"7G Rainbow Colony","Aayirathil Oruvan","Kushi","Mugavari","Dhill","Dhool","Saamy","Saamy 2",
"Arunachalam","Muthu","Padikkadavan","Murattu Kaalai",
"Thillu Mullu","Chandramukhi","Kochadaiiyaan","Lingaa",
"Varalaru","Citizen","Red","Villain","Dheena",
"Manmadhan","Vallavan","Silambattam","Osthe",
"Sarkar","Thalaivaa","Azhagiya Tamil Magan","Puli",
"Thirupaachi","Sivakasi","Kuruvi","Villu",
"Kaavalan","Friends","Uthama Puthiran","Velayudham",
"Aram","Kolamavu Kokila","Netrikann","Connect",
"Game Over","Kaatru Veliyidai","Chekka Chivantha Vaanam",
"Raavanan","Ayutha Ezhuthu","Kannathil Muthamittal",
"Thozha","Oopiri","Paiyaa","Siruthai",
"Veeram","Sandakozhi","Sandakozhi 2","Run",
"Run Baby Run","Thadam","Eetti","Boomerang",
"Kuttram 23","Irumbu Thirai","Hero","Ayogya",
"Comali","Love Today","Oh My Kadavule",
"Darling","Trisha Illana Nayanthara","Kalakalappu","Kalakalappu 2",
"Soodhu Kavvum","Naduvula Konjam Pakkatha Kaanom","Moodar Koodam",
"Tamizh Padam","Tamizh Padam 2","Boss Engira Baskaran",
"Oru Kal Oru Kannadi","Varuthapadatha Valibar Sangam",
"Rajini Murugan","Seema Raja","Prince",
"Mark Antony","Maaveeran","Mandela","Maara",
"Sillu Karuppatti","Good Night","Parking","Ayothi",
"Viduthalai","Viduthalai 2","Por Thozhil","Theeran Adhigaaram Ondru",
"Thani Oruvan","Bogan","Romeo Juliet",
"Idharkuthane Aasaipattai Balakumara",
"Pattas","Maaran","Captain","Enemy",
"Sketch","Komban","Viruman",
"Naan Kadavul","Pithamagan","Sethu",
"Kaadhalum Kadandhu Pogum","Aruvi",
"Magamuni","Joker","Peranbu",
"Thanga Meengal","Kutty","Thulluvadho Ilamai",
"Boys","Jeans","Gentleman",
"Mudhalvan","Anniyan","I","2.0","Ayalaan",
"Thiruda Thiruda","Kadhalan","Uzhavan",
"Poove Unakkaga","Priyamanavale","Unnai Ninaithu",
"Unakkaga Ellam Unakkaga","Thulladha Manamum Thullum",
"Ghajini","Vel","Vettai",
"Raatchasi","Taramani","Sindhubaadh",
"Psycho","Dhuruvangal Pathinaaru",
"8 Thottakkal","Kurangu Bommai","Meyaadha Maan",
"Mercury","Kanaa","Adanga Maru",
"Meesaya Murukku","Irudhi Suttru",
"V1 Murder Case","Lens","Andhaghaaram",
"Writer","Saani Kaayidham","Rocky",
"Mafia","Kalathil Sandhippom",
"Sabhaapathy","Malaysia to Amnesia",
"Plan Panni Pannanum","Hostel",
"Veetla Vishesham",
"Dada","Blue Star",
"Star","Japan",
"Lover",
"Viduthalai Part 1","Viduthalai Part 2",
"Garudan","Siragan","Weapon",
"Indian 3","Thangalaan","Kanguva",
"Retro","DD Returns","Conjuring Kannappan",
"Rangoli","Fight Club","Infinity",
"Sync","Diary",
"Yaanai","Gatta Kusthi","DSP",
"Naai Sekar Returns","Cobra",
"Etharkkum Thunindhavan",
"Mahaan","Hey Sinamika",
"Sulthan",
"Thittam Irandu","Udanpirappe","Navarasa",
"Paava Kadhaigal","Ponniyin Selvan 1","Ponniyin Selvan 2"
];

module.exports = movies;
