const movies = [
  "Ponniyin Selvan: I",
  "The Greatest of All Time",
  "Leo",
  "Jailer",
  "Vikram",
  "Coolie",
  "Amaran",
  "Varisu",
  "Bigil",
  "Enthiran",
  "Sarkar",
  "Vettaiyan",
  "Mersal",
  "Darbar",
  "I",
  "Master",
  "Petta",
  "Vishwaroopam",
  "Beast",
  "Good Bad Ugly",
  "Dasavathaaram",
  "Thuppakki",
  "Kaththi",
  "Theri",
  "Kabali",
  "Kaala",
  "Viswasam",
  "Nerkonda Paarvai",
  "Valimai",
  "Thunivu",
  "Raayan",
  "Captain Miller",
  "Ayalaan",
  "Lal Salaam",
  "Indian 2",
  "Kanguva",
  "Thangalaan",
  "Garudan",
  " Maharaja",
  "Aranmanai 4",
  "Lover",
  "Blue Star",
  "Vadakkupatti Ramasamy",
  "Ayali",
  "Chithha",
  "Jigarthanda DoubleX",
  "Japan",
  "Mark Antony",
  "Por Thozil",
  "Maamannan",
  "Pathu Thala",
  "Vaathi",
  "Varalaru",
  "Ghilli",
  "Pokkiri",
  "Sachein",
  "Thirumalai",
  "Saamy",
  "Dhool",
  "Run",
  "Kaakha Kaakha",
  "Pithamagan",
  "Anniyan",
  "Ghajini",
  "Vaaranam Aayiram",
  "Ayan",
  "Vettaiyaadu Vilaiyaadu",
  "Minnale",
  "Lesa Lesa",
  "Khushi",
  "Ullam Kollai Poguthae",
  "Dheena",
  "Friends",
  "Thenali",
  "Kandukondain Kandukondain",
  "Alaipayuthey",
  "Sethu",
  "Padayappa",
  "Baashha",
  "Muthu",
  "Apoorva Sagodharargal",
  "Nayagan",
  "Sadalima",
  "Thalapathi",
  "Anbe Sivam",
  "Panchatanthiram",
  "Pammal K. Sambandam",
  "Virumandi",
  "Hey Ram",
  "Kandukondain Kandukondain",
  "Mahanadhi",
  "Thevar Magan",
  "Aarilirunthu Arubathu Varai",
  "Moondram Pirai",
  "16 Vayathinile",
  "Sollathane Ninaikkiren",
  "Kadalikka Neramillai",
  "Veerapandiya Kattabomman",
  "Karnan",
  "Saraswathi Sabatham",
  "Thiruvilaiyaadal",
  "Billa",
  "Theeradha Vilaiyatu Pillai",
  "Mankatha",
  "Billa II",
  "Arrambam",
  "Yennai Arindhaal",
  "Vedalam",
  "Vivegam",
  "Viswasam",
  "Nandha",
  "Thulluvadho Ilamai",
  "Kadhal",
  "Paruthiveeran",
  "Subramaniapuram",
  "Naadodigal",
  "Pasanga",
  "Aadukalam",
  "Mankatha",
  "Pizza",
  "Soodhu Kavvum",
  "Neram",
  "Thalaimuraigal",
  "Kadal",
  "Raja Rani",
  "Arrambam",
  "Naveena Saraswathi Sabatham",
  "Biriyani",
  "Jigarthanda",
  "Kaththi",
  "Madras",
  "Velaiilla Pattadhari",
  "Mundasupatti",
  "Goli Soda",
  "Jiiva",
  "Kaaka Muttai",
  "Ok Kanmani",
  "Thani Oruvan",
  "Naanum Rowdydhaan",
  "Maya",
  "Pasanga 2",
  "Trisha Illana Nayanthara",
  "Rajini Murugan",
  "Irudhi Suttru",
  "Theri",
  "Kudumbangal Kondadum Vetri",
  "Pichaikkaran",
  "Metro",
  "Kabali",
  "Iru Mugan",
  "Remo",
  "Kodi",
  "Dhuruvangal Pathinaaru",
  "Bairavaa",
  "Si3",
  "Kavan",
  "Pa Paandi",
  "Vikram Vedha",
  "Sangili Bungili Kadhava Thorae",
  "Vanamagan",
  "Tubelight",
  "Gemini Ganeshanum Suruli Raajanum",
  "Thupparivalan",
  "Mersal",
  "Theeran Adhigaaram Ondru",
  "Velaikkaran",
  "Aruvi",
  "Gulaebaghavali",
  "Sketch",
  "Thaanaa Serndha Kootam",
  "Nagesh Thiraiyarangam",
  "Madura Veeran",
  "Mannar Vagaiyara",
  "Ghajinikanth",
  "Diya",
  "Irumbu Thirai",
  "Kaali",
  "Tik Tik Tik",
  "Kadaikutty Singam",
  "Kolamavu Kokila",
  "Pariyerum Perumal",
  "96",
  "Chekka Chivantha Vaanam",
  "Sandakozhi 2",
  "Ratsasan",
  "Sarkar",
  "Vada Chennai",
  "Seethakaathi",
  "Kanaa",
  "Petta",
  "Viswasam",
  "LKG",
  "Dev",
  "Kuppathu Raja",
  "Ayogya",
  "NGK",
  "Dharmadurai",
  "Comali",
  "Kaappaan",
  "Namma Veetu Pillai",
  "Bigil",
  "Kaithi",
  "Asuran",
  "Action",
  "Sangathamizhan",
  "Enai Noki Paayum Thota",
  "Dhanusu Raasi Neyargale",
  "Darbar",
  "Psycho",
  "Pattas",
  "Oh My Kadavule",
  "Dharala Prabhu",
  "Kannum Kannum Kollaiyadithaal",
  "Soorarai Pottru",
  "Master",
  "Karnan",
  "Sulthan",
  "Jagame Thanthiram",
  "Sarpatta Parambarai",
  "Doctor",
  "Jai Bhim",
  "Maanaadu",
  "Etharkkum Thunindhavan",
  "Beast",
  "Don",
  "Vikram",
  "Viruman",
  "Thiruchitrambalam",
  "Sardar",
  "Love Today",
  "Varisu",
  "Thunivu",
  "Pathu Thala",
  "Viduthalai Part 1",
  "Ponniyin Selvan: II",
  "Maamannan",
  "Jailer",
  "Leo",
  "Jigarthanda DoubleX",
  "Chithha",
  "Ayalaan",
  "Captain Miller",
  "Raayan",
  "Indian 2",
  "Maharaja",
  "Kanguva",
  "Vettaiyan",
  "The Greatest of All Time",
  "Amaran",
  "Kadaisi Vivasayi",
  "Mandela",
  "Koozhangal",
  "Rocky",
  "Kuruthi Aattam",
  "Cobra",
  "Prince",
  "Sardar",
  "Coffee with Kadhal",
  "Gatta Kusthi",
  "Driver Jamuna",
  "Varalaru Ththarunam",
  "Bakasura",
  "Agilan",
  "Vaathi",
  "Dada",
  "Run Baby Run",
  "Bagheera",
  "Kodai",
  "Viduthalai Part 2",
  "Thangalaan",
  "Kanguva",
  "Retro",
  "Aayirathil Oruvan",
  "Mayan",
  "Pudhupettai",
  "Kaadhal Kondein",
  "7G Rainbow Colony",
  "Pattiyal",
  "Arinthum Ariyamalum",
  "Sandakozhi",
  "Ghajini",
  "Jiva",
  "Thirupaachi",
  "Sivakasi",
  "Paramasivan",
  "Aathi",
  "Azhagiya Tamizh Magan",
  "Kuruvi",
  "Vettaikaaran",
  "Sura",
  "Velayudham",
  "Nanban",
  "Thuppakki",
  "Thalaivaa",
  "Jilla",
  "Kaththi",
  "Puli",
  "Theri",
  "Bairavaa",
  "Mersal",
  "Sarkar",
  "Bigil",
  "Master",
  "Beast",
  "Varisu",
  "Leo",
  "The Greatest of All Time",
  "Ghilli",
  "Madurey",
  "Thirumalai",
  "Youth",
  "Badri",
  "Kushi",
  "Priyamaanavale",
  "Nila Kaalam",
  "Mugavaree",
  "Ezhai Jaathi",
  "Suyamvaram",
  "Housefull",
  "Unnidathil Ennai Koduthen",
  "Kaadhale Nimmadhi",
  "Love Today",
  "Gokulathil Seethai",
  "Poove Unakkaga",
  "Coimbatore Mappillai",
  "Karisakkaadu",
  "Muthal Mariyathai",
  "Chinna Gounder",
  "Ejamaan",
  "Sethupathi IPS",
  "Kizhakku Cheemayile",
  "Gentleman",
  "Kadhalan",
  "Indian",
  "Minsara Kanavu",
  "Ratchagan",
  "Jeans",
  "Kandukondain Kandukondain",
  "Mudhalvan",
  "Kushi",
  "Friends",
  "Thenali",
  "Minnale",
  "Dheena",
  "Citizen",
  "Star",
  "Alli Thandha Vaanam",
  "Majunu",
  "Shahjahan",
  "Aalavandhan",
  "Vaali",
  "Nee Varuvai Ena",
  "Housekeeper",
  "Sethu",
  "Jodi",
  "Poovellam Kettuppar",
  "Padayappa",
  "Thulladha Manamum Thullum",
  "Nina പ്രത്യേகமான",
  "En Swasa Kaatre",
  "Kadhala Kadhala",
  "Santhosham",
  "Ulavuthurai",
  "Bharathi",
  "Karisakattu Poove",
  "Vetri Kodi Kattu",
  "Pennin Manathai Thottu",
  "Parthen Rasithen",
  "Kanna Laddu Thinna Aasaiya",
  "Soodhu Kavvum",
  "Theeya Velai Seiyyanum Kumaru",
  "Varuthapadatha Valibar Sangam",
  "Thalaivaa",
  "Naiyaandi",
  "Raja Rani",
  "Vanakkam Chennai",
  "Arrambam",
  "Pandiya Naadu",
  "Biriyani",
  "Veeram",
  "Jilla",
  "Goli Soda",
  "Maan Karate",
  "Velaiilla Pattadhari",
  "Jigarthanda",
  "Anjaan",
  "Kaththi",
  "Poojai",
  "Kaaki Sattai",
  "Yennai Arindhaal",
  "Kanchana 2",
  "3",
  "Neethaane En Ponvasantham",
  "Nanban",
  "Kalakalappu",
  "Saguni",
  "Thuppakki",
  "Maatraan",
  "Pizza",
  "Sundarapandian",
  "Kumki",
  "Thalaimuraigal",
  "Vishwaroopam",
  "Kedi Billa Killadi Ranga",
  "Ethir Neechal",
  "Theeya Velai Seiyyanum Kumaru",
  "Singam II",
  "Maryan",
  "Thalaivaa",
  "All in All Azhagu Raja",
  "Biriyani",
  "Aranmanai",
  "Kaaviya Thalaivan",
  "Vellakkara Durai",
  "I",
  "Darling",
  "Komban",
  "Kaaka Muttai",
  "Massu Engira Masilamani",
  "Romeo Juliet",
  "Papanasam",
  "Vaalu",
  "Thani Oruvan",
  "Maari",
  "Pa Paandi",
  "Savarakathi",
  "Tik Tik Tik",
  "Kaala",
  "Imaikkaa Nodigal",
  "Seethakaathi",
  "Viswasam",
  "Petta",
  "Peranbu",
  "Thadam",
  "Kanchana 3",
  "NGK",
  "Ayogya",
  "Comali",
  "Kaappaan",
  "Namma Veetu Pillai",
  "Bigil",
  "Kaithi",
  "Asuran",
  "Dhamaka",
  "Master",
  "Doctor",
  "Jai Bhim",
  "Maanaadu",
  "Etharkkum Thunindhavan",
  "Beast",
  "Don",
  "Vikram",
  "Viruman",
  "Thiruchitrambalam",
  "Sardar",
  "Love Today",
  "Varisu",
  "Thunivu",
  "Pathu Thala",
  "Viduthalai Part 1",
  "Ponniyin Selvan: II",
  "Maamannan",
  "Jailer",
  "Leo",
  "Jigarthanda DoubleX",
  "Chithha",
  "Ayalaan",
  "Captain Miller",
  "Raayan",
  "Indian 2",
  "Maharaja",
  "Kanguva",
  "Vettaiyan",
  "The Greatest of All Time",
  "Amaran",
  "Good Bad Ugly",
  "Coolie"
];

module.exports = movies;
