const movies = [
    "Transformers",
    "F1",
    "Money Heist",
    "Stranger Things",
    "Pacific Rim",
    "Harry Potter",
    "Need for Speed",
    "Fast and Furious",
    "Iron Man",
    "Avatar",
    "Black Panther",
    "Thor",
    "Avengers: Age of Ultron",
    "Avengers: Endgame",
    "Doomsday",
    "Avengers: Civil War",
    "Justice League",
    "Aquaman",
    "Batman",
    "Superman",
    "The Flash",
    "Star Wars",
    "Guardians of the Galaxy",
    "Mission: Impossible",
    "Bad Boys",
    "Cobra Kai",
    "The Karate Kid",
    "John Wick",
    "Game of Thrones",
    "House of the Dragon",
    "The Witcher",
    "Kraven the Hunter",
    "Pirates of the Caribbean",
    "Alice in Borderland",
    "Alice in Wonderland",
    "Fantastic Four",
    "Fantastic Beasts",
    "Teenage Mutant Ninja Turtles",
    "Avengers: Infinity War",
    "Doctor Strange",
    "Captain America: The Winter Soldier",
    "Spider-Man",
    "The Amazing Spider-Man",
    "Spider-Man: Far From Home",
    "The Vampire Diaries",
    "The Odyssey",
    "Interstellar",
    "Oppenheimer",
    "Peaky Blinders",

    "Aadukalam",
    "Boss Engira Bhaskaran",
    "Vinnaithaandi Varuvaayaa",
    "Enthiran",
    "Paiyaa",
    "Angadi Theru",
    "Madrasapattinam",
    "Singam",
    "Mynaa",
    "Naan Mahaan Alla",
    "Deiva Thirumagal",
    "Ko",
    "Mankatha",
    "7aum Arivu",
    "Vettai",
    "Nanban",
    "Pizza",
    "Naan",
    "Mugamoodi",
    "Thuppakki",
    "Neerparavai",
    "Kumki",
    "Sundarapandian",
    "Pizza 2: The Villa",
    "Kadal",
    "Ethir Neechal",
    "Maryan",
    "Raja Rani",
    "Varuthapadatha Valibar Sangam",
    "Jigarthanda",
    "Velaiilla Pattadhari",
    "Maan Karate",
    "Madras",
    "Kaththi",
    "Pisasu",
    "Mundasupatti",
    "Goli Soda",
    "Indru Netru Naalai",
    "Kaakkaa Muttai",
    "Darling",
    "Yennai Arindhaal",
    "I",
    "OK Kanmani",
    "Komban",
    "Kakki Sattai",
    "Demont Colony",
    "Thani Oruvan",
    "Papanasam",
    "Naanum Rowdy Dhaan",
    "Maari",
    "Vedalam",
    "Eetti",
    "Pasanga 2",
    "Visaranai",
    "Irudhi Suttru",
    "Kadhalum Kadandhu Pogum",
    "Theri",
    "Kabali",
    "24",
    "Achcham Enbadhu Madamaiyada",
    "Kodi",
    "Aandavan Kattalai",
    "Joker",
    "Kavan",
    "Maanagaram",
    "Vikram Vedha",
    "Theeran Adhigaaram Ondru",
    "Mersal",
    "Velaikkaran",
    "Aruvi",
    "Ratsasan",
    "Pariyerum Perumal",
    "96",
    "Vada Chennai",
    "Chekka Chivantha Vaanam",
    "Kaala",
    "2.0",
    "Kolamaavu Kokila",
    "Imaikkaa Nodigal",
    "Pyaar Prema Kaadhal",
    "Seema Raja",
    "Kaatrin Mozhi",
    "Maari 2",
    "Silukkuvarpatti Singam",
    "Adanga Maru",
    "Thadam",
    "Super Deluxe",
    "Petta",
    "Viswasam",
    "LKG",
    "Monster",
    "Aadai",
    "Kadhal Sadugudu",
    "Dharala Prabhu",
    "Oh My Kadavule",
    "Kannum Kannum Kollaiyadithaal",
    "Pattas",
    "Psycho",
    "Asuran",
    "Bigil",
    "Kaithi",
    "Namma Veettu Pillai",
    "Hero",
    "Comali",
    "Soorarai Pottru",
    "Paava Kadhaigal",
    "Mookuthi Amman",
    "Sarpatta Parambarai",
    "Jai Bhim",
    "Doctor",
    "Maanaadu",
    "Master",
    "Karnan",
    "Mandela",
    "Nenjam Marappathillai",
    "Jagame Thandhiram",
    "Maanadu",
    "Sivakumarin Sabadham",
    "Bachelor",
    "Dikkiloona",
    "Lift",
    "Vikram",
    "Beast",
    "Don",
    "Kaathuvaakula Rendu Kaadhal",
    "Thiruchitrambalam",
    "Ponniyin Selvan: Part I",
    "Vendhu Thanindhathu Kaadu",
    "Love Today",
    "Gatta Kusthi",
    "Naai Sekar Returns",
    "Viruman",
    "Sita Ramam",
    "Dada",
    "Good Night",
    "Por Thozhil",
    "Maamannan",
    "Viduthalai Part 1",
    "Ponniyin Selvan: Part II",
    "Jailer",
    "Leo",
    "Mark Antony",
    "Chithha",
    "Parking",
    "Blue Star",
    "Ayalaan",
    "Captain Miller",
    "Aranmanai 4",
    "Maharaja",
    "Raayan",
    "Indian 2",
    "Amaran",
    "Vettaiyan",
    "GOAT",
    "Lubber Pandhu",
    "Meiyazhagan",
    "Kottukkaali",
    "Vaazhai",
    "Garudan",
    "Demonte Colony 2",
    "Thangalaan",
    "Lover",
    "Singapore Saloon",
    "The Greatest of All Time",
    "Kanguva",
    "Tourist Family",
    "Dragon",
    "Kudumbasthan",
    "Bison",
    "Eleven",
    "Dude",
    "Kaantha",
    "Coolie",
    "Kuberaa",
    "Retro",
    "Idli Kadai",
    "Sirai",
    "Veera Dheera Sooran",
    "Vidaamuyarchi",
    "Good Bad Ugly",
    "Madha Gaja Raja",
    "Autograph",
    "Vaaranam Aayiram",
    "Ayan",
    "Aasal",
    "Sura",
    "Engeyum Eppodhum",
    "Saguni",
    "Alex Pandian",
    "All in All Azhagu Raja",
    "Biriyani",
    "Massu Engira Masilamani",
    "Kaashmora",
    "Dev",
    "Mr. Local",
    "Seemaraja",
    "Rajinimurugan",
    "Remo",
    "Sivaji",
    "Kuruvi",
    "Velayudham",
    "Thalaivaa",
    "Jilla",
    "Puli",
    "Bairavaa",
    "Sarkar",
    "Darbar",
    "Lingaa",
    "Kochadaiiyaan",
    "Annaatthe",
    "Kaaki Sattai",
    "Velaiilla Pattadhari 2",
    "Naane Varuven",
    "Anegan",
    "Polladhavan",
    "Padikathavan",
    "Uthama Puthiran",
    "3",
    "VIP 2",
    "Vaathi",
    "Kaathadi",
    "Irandam Ulagam",
    "Kakka Kakka",
    "Maattrraan",
    "7 Aum Arivu",
    "Singam 2",
    "Singam 3",
    "Iru Mugan",
    "Cobra",
    "Mahaan",
    "Kadaram Kondan",
    "Sketch",
    "Saamy 2",
    "10 Endrathukulla",
    "Saamy Square",
    "Pithamagan",
    "Anjaan",
    "NGK",
    "Aayirathil Oruvan",
    "Mayakkam Enna",
    "7G Rainbow Colony",
    "Pudhupettai",
    "Kandukondain Kandukondain",
    "Irandaam Ulagam",
    "Saani Kaayidham",
    "Mafia: Chapter 1",
    "Iraivi",
    "Jigarthanda Double X",
    "Soodhu Kavvum",
    "Pizza II: Villa",
    "Meyaadha Maan",
    "Mamannan",
    "Viduthalai Part 2",
    "Attakathi",
    "Abhiyum Naanum",
    "Mozhi",
    "Mouna Ragam",
    "Sillunu Oru Kadhal",
    "Alaipayuthey",
    "Kushi",
    "Sivakarthikeyan",
    "Rajini Murugan",
    "Prince",
    "Kedi Billa Killadi Ranga",
    "Tamil Padam",
    "Tamil Padam 2",
    "Kalakalappu",
    "Kalakalappu 2",
    "Vaagai Sooda Vaa",
    "Naduvula Konjam Pakkatha Kaanom",
    "Demonte Colony",
    "Eeram",
    "Yaavarum Nalam",
    "Maya",
    "Game Over",
    "Andhaghaaram",
    "Bhoomi",
    "Tumbbad",
    "Siren",
    "Rudhran",
    "Sardar",
    "Irumbu Thirai",
    "Raatchasi",
    "Kadaikutty Singam",
    "Maruthu",
    "Kutti Puli",
    "Taanakkaran"
];

module.exports = movies;
